os: Visual Studio 2017
version: build{build}

image: Visual Studio 2017

branches:
  only:
  - master

environment:
  SpecFlowBaseVersion: 3.0.0
  SpecFlowPackageVersion: "3.0.0-ci$(APPVEYOR_BUILD_NUMBER)"

cache:
  - packages -> **\packages.config

nuget:
  project_feed: true
  disable_publish_on_pr: true

configuration: Debug

before_build:
- cmd: dotnet restore

build:
  project: TechTalk.SpecFlow.sln
  verbosity: normal

test_script:
- vstest.console /logger:Appveyor "Tests\TechTalk.SpecFlow.RuntimeTests\bin\Debug\net461\TechTalk.SpecFlow.RuntimeTests.dll"
- vstest.console /logger:Appveyor "Tests\TechTalk.SpecFlow.GeneratorTests\bin\Debug\net461\TechTalk.SpecFlow.GeneratorTests.dll"
- vstest.console /logger:Appveyor "Tests\TechTalk.SpecFlow.Specs\bin\Debug\net461\TechTalk.SpecFlow.Specs.dll"
- vstest.console /logger:Appveyor "Tests\TechTalk.SpecFlow.IntegrationTests\bin\Debug\net461\TechTalk.SpecFlow.IntegrationTests.dll"

artifacts:
- path: '\artifacts\SpecFlow.*.nupkg'
